import type { Metadata } from "next";
import { Fira_Code } from "next/font/google";

import "./globals.css";

const firaCode = Fira_Code({
  weight: ["600"],
  subsets: ["latin"],
  variable: "--fira-code",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${firaCode.className} antialiased`}>{children}</body>
    </html>
  );
}
